title: office.com/setup home & student 2019 login || Office Home Student
description: Open the Office app. On the Recent screen, tap Sign In. On the Sign In screen, type the email address and password you use with Office.
